Repository vmware-tanzu/tanzu-plugin-runtime, pull requests merged in 2023-04, with the labels that each got.

#42 Add APIs for CEIPOptIn configuration
  config/cli_options_nextgen.go
  config/cli_options_nextgen_test.go
  config/config_keys.go
  config/types/clientconfig_types.go
Labels: cla-not-required

#40 Update documentation for Config APIs and Cross-version API compatibility testing
  README.md
  docs/config.md
  test/compatibility/docs/cross-version-api-compatibility-framework.md
  test/compatibility/docs/cross-version-api-compatibility.md
Labels: cla-not-required

#38 Add GitHub badge for compatibility tests workflow
  .github/workflows/compatibility_tests.yaml
  README.md
Labels: cla-not-required

#47 Fix Test plugin to include Target by default
  test/framework/framework.go
Labels: bug, cla-not-required

#49 Add docs for framework plugin test helpers
  test/framework/README.md
Labels: cla-not-required, area/docs

#50 Add support doc, update links
  CONTRIBUTING.md
  README.md
  docs/community/support.md
  docs/config.md
Labels: cla-not-required

#51 Add release workflow to produce github release on tag
  .github/workflows/release.yaml
Labels: cla-not-required

#52 Update development notice
  README.md
Labels: cla-not-required

#56 Update golangci-lint to 1.52.2
  .github/workflows/main.yaml
  .golangci.yaml
  component/output.go
  config/contexts.go
  config/discovery_sources_node.go
  config/fileutil.go
  hack/tools/Makefile
  log/logger.go
  test/compatibility/framework/context_commands.go
  test/compatibility/framework/server_commands.go
  test/compatibility/testplugins/runtime-test-plugin-latest/cmd/parser.go
  test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_server_apis.go
  test/exec/command.go
  test/framework/framework.go
  test/plugins/helloworld/print.go
Labels: cla-not-required

#35 Cross-version API Compatibility - Cleanup Test Helper functions
  .github/workflows/compatibility_tests.yaml
  test/compatibility/core/api_constants.go
  test/compatibility/docs/cross-version-api-compatibility-framework.md
  test/compatibility/docs/cross-version-api-compatibility.md
  test/compatibility/framework/compatibilitytests/common/test_helpers.go
  test/compatibility/framework/compatibilitytests/context/context_test.go
  test/compatibility/framework/compatibilitytests/context/context_test_helpers.go
  test/compatibility/framework/compatibilitytests/contextserver/context_and_server_test.go
  test/compatibility/framework/compatibilitytests/server/server_test.go
  test/compatibility/framework/compatibilitytests/server/server_test_helpers.go
  test/compatibility/framework/validators/testcase_validator.go
  test/compatibility/testplugins/runtime-test-plugin-latest/cmd/trigger_apis.go
  test/compatibility/testplugins/runtime-test-plugin-v0_11_6/cmd/trigger_apis.go
  test/compatibility/testplugins/runtime-test-plugin-v0_25_4/cmd/trigger_apis.go
  test/compatibility/testplugins/runtime-test-plugin-v0_28_0/cmd/trigger_apis.go
Labels: cla-not-required

#55 Use generics to convert objects to config nodes
  config/cli_repositories.go
  config/clientconfig_factory.go
  config/clientconfignextgen_factory_test.go
  config/contexts.go
  config/conversion.go
  config/discovery_sources_node.go
  config/metadata_factory.go
  config/servers.go
Labels: cla-not-required

#60 Run Compatibility tests on all PRs
  .github/workflows/compatibility_tests.yaml
Labels: cla-not-required

#58 Move the DiscoverySources config section
  config/cli_discovery_sources.go
  config/cli_discovery_sources_it_test.go
  config/cli_discovery_sources_test.go
  config/config_factory_test.go
  config/legacy_clientconfig_factory.go
  config/legacy_clientconfig_factory_test.go
  config/patchstrategy_it_test.go
  config/types/clientconfig_types.go
Labels: cla-not-required

#62 Add configuration APIs for Certificate configuration
  config/certs.go
  config/certs_test.go
  config/config_keys.go
  config/conversion.go
  config/types/clientconfig_types.go
Labels: cla-not-required

#63 Add DefaultFeatureFlags inot PluginDescriptor to enable plugins to set default feature flags in config file
  plugin/types.go
Labels: cla-not-required
